name: ğŸ“¦ Build & Release Zip on Main

on:
  push:
    branches:
      - main

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: ğŸ›ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ” Create ZIP archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: release.zip
          path: "addons/"
          exclusions: '/.git,/**/*.github/*'

      - name: ğŸ“¦ Create or update Release on GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: release.zip
          allowUpdates: true
          generateReleaseNotes: false
          tag: main-release-${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
